### ISSUE TITLE
不能支持上传图片呢

### ISSUE THREAD

**Issue by helloworldtang** [wchstrife/blog#2]
不能支持上传图片呢

**Comment by yangjingsong** [comment]
缺少com.wchstrife.aspect.WebSecurityConfig这个文件吧

**Comment by wchstrife** [comment]
@yangjingsong 抱歉，似乎当时没有git add进去，我会再最近修复一下

**Comment by wchstrife** [comment]
@helloworldtang 有时间的话我会更新一下功能

**Comment by wchstrife** [comment]
@yangjingsong 已经把缺的部分push了上来
